name: Build Flatpak Bundle
on:
  workflow_dispatch:
  pull_request:

jobs:
  build-bundle:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Flatpak
        run:
          |
          sudo apt -qq update
          sudo apt -qq install -y flatpak flatpak-builder
          sudo flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
          sudo flatpak install -y org.freedesktop.Platform//24.08 org.freedesktop.Sdk//24.08 org.electronjs.Electron2.BaseApp//24.08
          git config --global protocol.file.allow always # https://github.com/flatpak/flatpak-builder/issues/495
      - name: Build
        run:
          |
          flatpak-builder --repo=repo build cn.kdocs.KDesktop.yaml --delete-build-dirs --force-clean
          flatpak build-bundle ./repo cn.kdocs.KDesktop.flatpak cn.kdocs.KDesktop
      - name: Get current date
        id: date
        run: echo "CURRENT_DATE=$(date -u '+%y%m%d%H%M')" >> $GITHUB_OUTPUT
      - name: Upload to Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flatpak-bundle
          path: cn.kdocs.KDesktop.flatpak
      - name: Upload to Release
        if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.date.outputs.CURRENT_DATE }}
          tag_name: ${{ steps.date.outputs.CURRENT_DATE }}
          files: cn.kdocs.KDesktop.flatpak
          body:
            |
            install via:
            ```
            flatpak install cn.kdocs.KDesktop.flatpak
            ```
